export const LOAD_DATABASES_REQUEST = 'LOAD_DATABASES_REQUEST';
export const LOAD_DATABASES_SUCCESS = 'LOAD_DATABASES_SUCCESS';
export const LOAD_DATABASES_FAILURE = 'LOAD_DATABASES_FAILURE';
export const LOAD_CONNECTIONS_SUCCESS = 'LOAD_CONNECTIONS_SUCCESS';
export const EXECUTE_QUERY_REQUEST = 'EXECUTE_QUERY_REQUEST';
export const EXECUTE_QUERY_SUCCESS = 'EXECUTE_QUERY_SUCCESS';
export const EXECUTE_QUERY_FAILURE = 'EXECUTE_QUERY_FAILURE';
export const UPDATE_SQL_SUCCESS = 'UPDATE_SQL_SUCCESS';
