export const SHOW_DIALOG = 'SHOW_DIALOG';
export const LODAD_DABATASES = 'LODAD_DABATASES';
export const LODAD_CONNECTIONS = 'LODAD_CONNECTIONS';
export const EXECUTE_QUERY = 'EXECUTE_QUERY';
export const FAIL_QUERY = 'FAIL_QUERY';
