// Config event keys
export const CONFIG_PREPARE = 'CONFIG_PREPARE';
export const CONFIG_PATH = 'CONFIG_PATH';
export const CONFIG_GET = 'CONFIG_GET';
export const CONFIG_GET_SYNC = 'CONFIG_GET_SYNC';
export const CONFIG_SAVE = 'CONFIG_SAVE';
export const CONFIG_SAVE_SETTINS = 'CONFIG_SAVE_SETTINS';

// Server event keys
export const SERVERS_GET_ALL = 'SERVERS_GET_ALL';
export const SERVERS_ADD = 'SERVERS_ADD';
export const SERVERS_UPDATE = 'SERVERS_UPDATE';
export const SERVERS_ADD_OR_UPDATE = 'SERVERS_ADD_OR_UPDATE';
export const SERVERS_REMOVE_BY_ID = 'SERVERS_REMOVE_BY_ID';
export const SERVERS_DECRYPT_SECRETS = 'SERVERS_DECRYPT_SECRETS';

// Logger event keys
export const LOGGER_ERROR = 'LOGGER_ERROR';

// DB event keys
export const DB_GET_CLIENTS_SYNC = 'DB_GET_CLIENTS_SYNC';
export const DB_HANDLE_SSH_ERROR = 'DB_HANDLE_SSH_ERROR';
export const DB_CHECK_IS_CONNECTED = 'DB_CHECK_IS_CONNECTED';
export const DB_CONNECT = 'DB_CONNECT';
export const DB_DISCONNECT = 'DB_DISCONNECT';
export const DB_GET_VERSION = 'DB_GET_VERSION';
export const DB_LIST_DATABASES = 'DB_LIST_DATABASES';
export const DB_LIST_SCHEMAS = 'DB_LIST_SCHEMAS';
export const DB_LIST_TABLES = 'DB_LIST_TABLES';
export const DB_LIST_VIEWS = 'DB_LIST_VIEWS';
export const DB_LIST_ROUTINES = 'DB_LIST_ROUTINES';
export const DB_LIST_TABLE_COLUMNS = 'DB_LIST_TABLE_COLUMNS';
export const DB_LIST_TABLE_TRIGGERS = 'DB_LIST_TABLE_TRIGGERS';
export const DB_LIST_TABLE_INDEXES = 'DB_LIST_TABLE_INDEXES';
export const DB_GET_TABLE_REFERENCES = 'DB_GET_TABLE_REFERENCES';
export const DB_GET_TABLE_KEYS = 'DB_GET_TABLE_KEYS';
export const DB_QUERY = 'DB_QUERY';
export const DB_EXECUTE_QUERY = 'DB_EXECUTE_QUERY';
export const DB_GET_QUERY_SELECT_TOP = 'DB_GET_QUERY_SELECT_TOP';
export const DB_GET_TABLE_CREATE_SCRIPT = 'DB_GET_TABLE_CREATE_SCRIPT';
export const DB_GET_TABLE_SELECT_SCRIPT = 'DB_GET_TABLE_SELECT_SCRIPT';
export const DB_GET_TABLE_INSERT_SCRIPT = 'DB_GET_TABLE_INSERT_SCRIPT';
export const DB_GET_TABLE_UPDATE_SCRIPT = 'DB_GET_TABLE_UPDATE_SCRIPT';
export const DB_GET_TABLE_DELETE_SCRIPT = 'DB_GET_TABLE_DELETE_SCRIPT';
export const DB_GET_VIEW_CREATE_SCRIPT = 'DB_GET_VIEW_CREATE_SCRIPT';
export const DB_GET_ROUTINE_CREATE_SCRIPT = 'DB_GET_ROUTINE_CREATE_SCRIPT';
export const DB_TRUNCATE_ALL_TABLES = 'DB_TRUNCATE_ALL_TABLES';
export const DB_GET_TABLE_COLUMN_NAMES = 'DB_GET_TABLE_COLUMN_NAMES';
export const DB_RESOLVE_SCHEMA = 'DB_RESOLVE_SCHEMA';
export const DB_WRAP = 'DB_WRAP';
