// Config event keys
export const CONFIG_PREPARE = 'CONFIG_PREPARE';
export const CONFIG_PATH = 'CONFIG_PATH';
export const CONFIG_GET = 'CONFIG_GET';
export const CONFIG_GET_FULL = 'CONFIG_GET_FULL';
export const CONFIG_GET_FULL_SYNC = 'CONFIG_GET_FULL_SYNC';
export const CONFIG_SAVE = 'CONFIG_SAVE';
export const CONFIG_SAVE_SETTINS = 'CONFIG_SAVE_SETTINS';

// Server event keys
export const SERVERS_GET_ALL = 'SERVERS_GET_ALL';
export const SERVERS_ADD = 'SERVERS_ADD';
export const SERVERS_UPDATE = 'SERVERS_UPDATE';
export const SERVERS_ADD_OR_UPDATE = 'SERVERS_ADD_OR_UPDATE';
export const SERVERS_REMOVE_BY_ID = 'SERVERS_REMOVE_BY_ID';
export const SERVERS_DECRYPT_SECRETS = 'SERVERS_DECRYPT_SECRETS';

// Logger event keys
export const LOGGER_ERROR = 'LOGGER_ERROR';

// DB event keys
export const DB_GET_CLIENTS_SYNC = 'DB_GET_CLIENTS_SYNC';
export const DB_CONNECT = 'DB_CONNECT';
export const DB_DISCONNECT_DATABASE = 'DB_DISCONNECT_DATABASE';
export const DB_DISCONNECT_SERVER = 'DB_DISCONNECT_SERVER';
export const DB_LIST_DATABASES = 'DB_LIST_DATABASES';
export const DB_LIST_SCHEMAS = 'DB_LIST_SCHEMAS';
export const DB_LIST_TABLES = 'DB_LIST_TABLES';
export const DB_LIST_VIEWS = 'DB_LIST_VIEWS';
export const DB_LIST_ROUTINES = 'DB_LIST_ROUTINES';
export const DB_LIST_TABLE_COLUMNS = 'DB_LIST_TABLE_COLUMNS';
export const DB_LIST_TABLE_TRIGGERS = 'DB_LIST_TABLE_TRIGGERS';
export const DB_LIST_TABLE_INDEXES = 'DB_LIST_TABLE_INDEXES';
export const DB_GET_TABLE_REFERENCES = 'DB_GET_TABLE_REFERENCES';
export const DB_GET_TABLE_KEYS = 'DB_GET_TABLE_KEYS';
export const DB_CREATE_CANCELLABLE_QUERY = 'DB_CREATE_CANCELLABLE_QUERY';
export const DB_CANCEL_CANCELLABLE_QUERY = 'DB_CANCEL_CANCELLABLE_QUERY';
export const DB_EXECUTE_CANCELLABLE_QUERY = 'DB_EXECUTE_CANCELLABLE_QUERY';
export const DB_EXECUTE_QUERY = 'DB_EXECUTE_QUERY';
export const DB_GET_QUERY_SELECT_TOP = 'DB_GET_QUERY_SELECT_TOP';
export const DB_GET_TABLE_CREATE_SCRIPT = 'DB_GET_TABLE_CREATE_SCRIPT';
export const DB_GET_TABLE_SELECT_SCRIPT = 'DB_GET_TABLE_SELECT_SCRIPT';
export const DB_GET_TABLE_INSERT_SCRIPT = 'DB_GET_TABLE_INSERT_SCRIPT';
export const DB_GET_TABLE_UPDATE_SCRIPT = 'DB_GET_TABLE_UPDATE_SCRIPT';
export const DB_GET_TABLE_DELETE_SCRIPT = 'DB_GET_TABLE_DELETE_SCRIPT';
export const DB_GET_VIEW_CREATE_SCRIPT = 'DB_GET_VIEW_CREATE_SCRIPT';
export const DB_GET_ROUTINE_CREATE_SCRIPT = 'DB_GET_ROUTINE_CREATE_SCRIPT';
export const DB_TRUNCATE_ALL_TABLES = 'DB_TRUNCATE_ALL_TABLES';
export const DB_GET_TABLE_COLUMN_NAMES = 'DB_GET_TABLE_COLUMN_NAMES';
export const DB_SET_SELECT_LIMIT = 'DB_SET_SELECT_LIMIT';

// Browser Dialog keys
export const BROWSER_DIALOG_SHOW_SAVE_DIALOG = 'BROWSER_DIALOG_SHOW_SAVE_DIALOG';
export const BROWSER_DIALOG_SHOW_OPEN_DIALOG = 'BROWSER_DIALOG_SHOW_OPEN_DIALOG';

// Browser FS keys
export const BROWSER_FS_SAVE_FILE = 'BROWSER_FS_SAVE_FILE';
export const BROWSER_FS_OPEN_FILE = 'BROWSER_FS_OPEN_FILE';

// Browser Menu keys
export const BROWSER_MENU_CTX_MENU_BUILD = 'BROWSER_MENU_CTX_MENU_BUILD';
export const BROWSER_MENU_CTX_MENU_POPUP = 'BROWSER_MENU_CTX_MENU_POPUP';

export const BROWSER_MENU_REFRESH_DATABASE = 'BROWSER_MENU_REFRESH_DATABASE';
export const BROWSER_MENU_OPEN_TAB = 'BROWSER_MENU_OPEN_TAB';
export const BROWSER_MENU_SHOW_DATABASE_DIAGRAM = 'BROWSER_MENU_SHOW_DATABASE_DIAGRAM';
export const BROWSER_MENU_EXECUTE_DEFAULT_QUERY = 'BROWSER_MENU_EXECUTE_DEFAULT_QUERY';
export const BROWSER_MENU_GET_SQL_SCRIPT_CREATE_TABLE = 'BROWSER_MENU_GET_SQL_SCRIPT_CREATE_TABLE';
export const BROWSER_MENU_GET_SQL_SCRIPT_SELECT = 'BROWSER_MENU_GET_SQL_SCRIPT_SELECT';
export const BROWSER_MENU_GET_SQL_SCRIPT_INSERT = 'BROWSER_MENU_GET_SQL_SCRIPT_INSERT';
export const BROWSER_MENU_GET_SQL_SCRIPT_UPDATE = 'BROWSER_MENU_GET_SQL_SCRIPT_UPDATE';
export const BROWSER_MENU_GET_SQL_SCRIPT_DELETE = 'BROWSER_MENU_GET_SQL_SCRIPT_DELETE';
export const BROWSER_MENU_OPEN_PREVIEW = 'BROWSER_MENU_OPEN_PREVIEW';

export const BROWSER_MENU_ZOOM_IN = 'BROWSER_MENU_ZOOM_IN';
export const BROWSER_MENU_ZOOM_OUT = 'BROWSER_MENU_ZOOM_OUT';
export const BROWSER_MENU_ZOOM_RESET = 'BROWSER_MENU_ZOOM_RESET';

export const BROWSER_MENU_QUERY_EXECUTE = 'BROWSER_MENU_QUERY_EXECUTE';
export const BROWSER_MENU_QUERY_TAB_NEW = 'BROWSER_MENU_QUERY_TAB_NEW';
export const BROWSER_MENU_QUERY_TAB_CLOSE = 'BROWSER_MENU_QUERY_TAB_CLOSE';
export const BROWSER_MENU_QUERY_SAVE = 'BROWSER_MENU_QUERY_SAVE';
export const BROWSER_MENU_QUERY_SAVE_AS = 'BROWSER_MENU_QUERY_SAVE_AS';
export const BROWSER_MENU_QUERY_OPEN = 'BROWSER_MENU_QUERY_OPEN';
export const BROWSER_MENU_QUERY_FOCUS = 'BROWSER_MENU_QUERY_FOCUS';
export const BROWSER_MENU_TOGGLE_DB_SEARCH = 'BROWSER_MENU_TOGGLE_DB_SEARCH';
export const BROWSER_MENU_TOGGLE_DB_OBJS_SEARCH = 'BROWSER_MENU_TOGGLE_DB_OBJS_SEARCH';

// Shell keys
export const BROWSER_SHELL_OPEN = 'BROWSER_SHELL_OPEN';

// Clipboard keys
export const BROWSER_CLIPBOARD_WRITE = 'BROWSER_CLIPBOARD_WRITE';

// WebFrame keys
export const BROWSER_WEB_FRAME_SET_ZOOM_FACTOR = 'BROWSER_WEB_FRAME_SET_ZOOM_FACTOR';

// Update keys
export const UPDATE_CHECK = 'UPDATE_CHECK';
export const UPDATE_AVAILABLE = 'UPDATE_AVAILABLE';
